### ISSUE TITLE
Project: calculating correlation

### ISSUE THREAD

**Issue by mara-nel** [mlavin/lecture-notes#1]
I know during a lecture you referenced which measure of correlation to use in the project but I have been unable to find it referenced in the spring2018.py file.

Additionally I recall some clarification about how to best handle dates for which pricing wasn't recorded, but this doesn't seem to be mentioned in spring2018.py either.

Any repeated clarification would be appreciated.

**Comment by mlavin** [comment]
I've added some clarifications here: https://github.com/mlavin/lecture-notes/commit/09e601607221d19fed698cd4dbf9d831bb2827fa Let me know if that still doesn't answer all of your questions.

**Comment by mlavin** [comment]
:sun_with_face: :rainbow:
